# Generated by Django 4.0.4 on 2022-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_post_color_post_color_four_post_color_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='color_four',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='size',
            new_name='size_four',
        ),
        migrations.RemoveField(
            model_name='post',
            name='color_one',
        ),
        migrations.RemoveField(
            model_name='post',
            name='color_three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='color_two',
        ),
        migrations.AddField(
            model_name='post',
            name='size_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='size_three',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='size_two',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
