# Generated by Django 4.0.4 on 2022-05-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_carusel_alter_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
    ]
