# Generated by Django 4.0.4 on 2022-05-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='rasmlar/')),
                ('imageTitle', models.CharField(max_length=255)),
                ('buttonText', models.CharField(max_length=255)),
            ],
        ),
    ]
