# Generated by Django 4.0.4 on 2022-05-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_categorymonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMonthTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorymonth',
            name='text',
        ),
        migrations.RemoveField(
            model_name='categorymonth',
            name='title',
        ),
    ]
