# Generated by Django 4.0.4 on 2022-05-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_ourservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurServices',
            new_name='OurService',
        ),
    ]
