# Generated by Django 4.0.4 on 2022-05-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_ourservices_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServiceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='OurService',
            new_name='OurServiceCard',
        ),
        migrations.RenameField(
            model_name='ourservicecard',
            old_name='title',
            new_name='textIcon',
        ),
    ]
